name = "ZXCalculus"
uuid = "3525faa3-032d-4235-a8d4-8c2939a218dd"
authors = ["Chen Zhao and contributors"]
version = "0.2.2"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Multigraphs = "7ebac608-6c66-46e6-9856-b5f43e107bac"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LightGraphs = "1.3"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
